### ISSUE TITLE
Support RC2 compiler

### ISSUE THREAD

**Issue by djnicholson** [ngdenterprise/neo-tutorials#10]
Version will be 3.0.0-rc2 and the command line is changing from `neon` to `nccs`. Also need to pass --debug and --no-optimize in order to generate debuggable output

See: https://github.com/ngdenterprise/neo-registrar-sample/blob/devhawk/rc2/src/registrar.csproj#L9

**Comment by devhawk** [comment]
FYI, the RC2 version of Neo.BuildTasks will automatically trigger nccs during build if you set the `TargetNeoContractName` property.

from https://github.com/ngdenterprise/neo-registrar-sample/blob/master/src/registrar.csproj

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NeoExpressBatch>..\express.batch</NeoExpressBatch>
    <Nullable>enable</Nullable>
    <TargetFramework>net5.0</TargetFramework>
    <TargetNeoContractName>DevHawk.Registrar</TargetNeoContractName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Neo.BuildTasks" Version="1.0.25-preview" PrivateAssets="All" />
    <PackageReference Include="Neo.SmartContract.Framework" Version="3.0.0-rc2" />
  </ItemGroup>
</Project>
```

https://github.com/ngdenterprise/neo-fungible-token-sample has also been updated to use TargetNeoContractName

**Comment by devhawk** [comment]
Note, neo.BuildTasks automatically adds `--debug --no-optimize` for Debug builds

from https://github.com/ngdenterprise/neo-test/blob/main/src/build-tasks/build/Neo.BuildTasks.targets#L26

``` xml
  <Target Name="NccsBuild" AfterTargets="Build" Inputs="$(MSBuildProjectFullPath);@(Compile);" Outputs="$(TargetNeoContractPath);$(TargetNeoManifestPath);">
    <PropertyGroup>
      <_NccsDebugArguments Condition="'$(Configuration)'=='Debug'">--debug --no-optimize</_NccsDebugArguments>
      <_NccsDebugArguments Condition="'$(Configuration)'!='Debug'"></_NccsDebugArguments>
    </PropertyGroup>
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet nccs $(_NccsDebugArguments) $(MSBuildProjectFullPath)" />
  </Target>
```
