### ISSUE TITLE
Incompatibility with RC2

### ISSUE THREAD

**Issue by zlewe** [ngdenterprise/neo-tutorials#12]
Hi. While trying out the tutorials I found out a few compatibility issues with RC2. It might need to be updated because the tutorials are published on the hackathon site.
These issues are:

## 1. Namespaces changed
```
using Neo.SmartContract.Framework.Services.Neo;
using Neo.SmartContract.Framework.Services.System;
```
### Solution:
```
using Neo.SmartContract.Framework;
using Neo.SmartContract.Framework.Native;
using Neo.SmartContract.Framework.Services;
```

## 2. ExecutionEngine methods is moved to Runtime.
location: Register method in Registrar tutorial.
`var tx = (Transaction) ExecutionEngine.ScriptContainer;`
location: Transfer method in NEP token tutorial.
`from.Equals(ExecutionEngine.CallingScriptHash)`

### Solution:
`var tx = (Transaction) Runtime.ScriptContainer;`
`from.Equals(Runtime.CallingScriptHash)`

## 3. Storage.CurrentContext.CreateMap() method is removed.
location: NEP token tutorial
`private static StorageMap Balances => Storage.CurrentContext.CreateMap(MAP_NAME);`

### Solution: 
use StorageMap constructor
`private static StorageMap Balances => new StorageMap(Storage.CurrentContext, MAP_NAME);`

## 4. ToScriptHash() method not found.
location: NEP token tutorial
`static readonly Neo.UInt160 Owner = "NgP2WUaoLPyjcKwzRoBXJB5zxuXt8jts6u".ToScriptHash();`

### Solution: 
Explicitly cast the string to UInt160. (I'm not sure if this is correct and it is not tested yet)
`static readonly Neo.UInt160 Owner = (Neo.UInt160)"Ncz43ouEgDit9D188CSBhxfH7V2SxdPQUs";` 

Alternative found in Pet Shop example (Which I end up using):
Read owner from the transaction. 
```
var tx = (Transaction) Runtime.ScriptContainer;
var Owner = (Neo.UInt160) tx.Sender;
```

## Minor suggestion:
add namespace such that Neo.UInt160 can be written as UInt160
`using Neo;`

**Comment by djnicholson** [comment]
PR: https://github.com/ngdenterprise/neo-tutorials/pull/13
