### ISSUE TITLE
Create code tours directly in example's repositories

### ISSUE THREAD

**Issue by gsmachado** [ngdenterprise/neo-tutorials#6]
One of the best VSCode extensions I recently came across is the [Code Tour extension](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour). It's simply awesome. 🚀 

In my opinion, a lot of the content from the Neo Tutorial should be added as a code tour in each example repository.

Check out this example (more specifically, in the .tours folder):

https://github.com/neow3j/neow3j-examples-java/tree/master/neo-n3-examples

The good part is: you can have common tours explaining the tooling, and specific tours explaining the code.

The main rationale for migrating a lot from neo tutorials to code tours, in repos where examples are, is: if something changes (either in the tooling or in the example's code), you don't have to recreate the whole video -- you just need to update a single JSON with the whole explanation on it. 😄

**Comment by JohndeVadoss** [comment]
Yes @gsmachado We will be using this for one of the following set of quickstarts.

**Comment by gsmachado** [comment]
@JohndeVadoss the best part is that neo-playground.dev already supports "code tours" out of the box. 💪👍🙏 You guys should try it out, and maybe we could work together towards it.

**Comment by JohndeVadoss** [comment]
Adding to the backlog and closing the issue. Thank you Guil.
